### ISSUE TITLE
imapsync to O365

### ISSUE THREAD

**Issue by whyrukter** [imapsync/imapsync#104]
I try to sync mail from icewarp to O365 but seems have some error for line length exceeds.

- msg INBOX/116 skipped S[36419] F[\Seen] I[03-Aug-2017 17:00:34 +0700] (Subject:[=?UTF-8?Q?=E0=B8=9B=E0=B8=A3=E0=B8=B0=E0=B8=8A=E0=B8=B2=E0=B8=AA=E0=B8=B1=E0=B8=A1=E0=B8=9E=E0=B8=B1=E0=B8=99=E0=B8=98=E0=B9=8C=E0=B8=A3=E0=B8=B2=E0=B8=A2=E0=B8=81=E0=B8=B2=E0=B8=A3=E0=B8=95=E0=B9=88=E0=B8=B2=E0=B8=87=E0=B9=86_=E0=B8=82=E0=B8=AD=E0=B8=87=E0=B8=8A=E0=B9=88=E0=B8=AD=E0=B8=87_PPTV?=]) (line length exceeds maxlinelength 10500 bytes)

much appreciated if you can help

thanks

**Comment by gilleslamiral** [comment]
If the command line use --maxlinelength 10500 and a message has a line longer than 10500 bytes then imapsync skip it, as requested by --maxlinelength 10500. Use instead:
    
`imapsync ... --regexmess "s,(.{10500}),$1\r\n,g" `

It's explained in:
[https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt](url)

`=================================================================
Q. How to sync from XXX to Office365

R. Here is a command line resume that solves most encountered issues when 
   migrating to Office365. It's similar with Exchange except for some 
   values. To understand or change the details you have to read 
   next Q/R sections.


On Windows:

  imapsync.exe ... ^
    --maxsize 45000000 ^
    --maxmessagespersecond 4 ^
    --regexflag "s/\\Flagged//g" ^
    --disarmreadreceipts ^
    --regexmess "s,(.{10500}),$1\r\n,g"

On Unix:

  imapsync ... \
    --maxsize 45000000 \
    --maxlinelength 10500 \
    --maxmessagespersecond 4 \
    --regexflag 's/\\Flagged//g' \
    --disarmreadreceipts \
    --maxlinelengthcmd 'reformime -r7' 
    
On Linux, to get the "reformime" command, install the "maildrop" package.
In case you don't have it you can use 
  --regexmess 's,(.{10500}),$1\r\n,g'
instead of --maxlinelengthcmd 'reformime -r7' 

=================================================================`

**Comment by greem** [comment]
In my experience I've used --regexmess to reduce all lines down to no greater than 1000 chars + CRLF, which O365 seem to accept:

            --regexmess 's,(.{1000}),$1\r\n,g' \

I experimented with different values before settling at 1000. RFC5322 states 998 chars plus CRLF combination but 1000 worked for me quite reliably.

**Comment by gilleslamiral** [comment]
maxlinelength is applied after regexmess so transfer  should not skip any message, I have no clue to understand what happened to your case.

Anyway, do not rely on RFC advice to arbitrary impose  CRLNs inside messages, the less you transform messages the best it is. So biggest values are better.

**Comment by gilleslamiral** [comment]
Reading again Greem response I find that there was no problem to understand, he just put a small value to the wrapping  regexmess. 
I just wanted to mention that wrapping lines this way, adding \r\n, ie CRNL, is not safe, so the less it has  to be done (big value 10500), the better it is. 
Usually very long lines occur in Spam messages.
