### ISSUE TITLE
Average bandwidth  issue 

### ISSUE THREAD

**Issue by kumarsatin** [imapsync/imapsync#131]
Hi ,
          I should know why average bandwidth is different,when i am running imapsync.exe commond and imapsync source code perl script  from commond prompt and both give too much difference in average bandwidth.pls see screenshot of both log file 
imapsync.exe:-https://www.screencast.com/t/DvXmqeD3wU 
imapsync source file:- https://www.screencast.com/t/tmIxCvmsYz4g

**Comment by greem** [comment]
There's not really enough information to work with here. Are these for identical source messages, how many messages are there in each transfer, how much data, over what sort of time? How are the source and destination IMAP servers connected to each other - on a LAN, over a WAN, across the Internet at large? Do you control the end-to-end path?

If this is for a very small amount of data then I'd expect fairly wild variance in the averages.

If this is for a reasonably large amount of data (GB to TB) then maybe you've got a genuine problem here, but without that detail it's very hard to say.

**Comment by kumarsatin** [comment]
I am trying to migrate large mailbox around 10GB 
MAP servers connected to each other - on a LAN, over a WAN, across the Internet at large? 
over the internet:-for ex gmail mailbox
Do you control the end-to-end path?
no

**Comment by gilleslamiral** [comment]
If you encounter a bandwidth difference within the exact same conditions but the usage of imapsync.exe  instead of perl imapsync then I have no clue to explain that. 

If you encounter a bandwidth difference without the exact same conditions but the usage of imapsync.exe  instead of perl imapsync then I have many explanations to explain that, an explanation per different condition I dare say.

**Comment by kumarsatin** [comment]
I am  running both in  exact same conditions,But imapsync.exe (700 kib/s) bandwidth is faster rather than  imapsync perl script(160 kib/s).
pls see screen shot of log file
imapsync.exe:-https://www.screencast.com/t/DvXmqeD3wU
imapsync source file:- https://www.screencast.com/t/tmIxCvmsYz4g

**Comment by gilleslamiral** [comment]
Well, you don't have to send images repeating the values you give as text: I believe you. 
Is the difference  mostly the same when you repeat the experiment?

**Comment by gilleslamiral** [comment]
Thanks for the details.
I've done the experiment myself, same conditions: same imap servers, same accounts, same messages, same host running imapsync, and a deletion of host2 messages between two syncs. The only differences were the time (syncs are successive) and the execution of "perl imapsync" instead of "imapsync.exe". I repeated the syncs several times. The results?

You are definitively right! Like you the result is that the average bandwidth can be very different! 

But it is different in any sense, sometimes it is "perl imapsync", sometimes it is "imapsync.exe". 
If I monitor the hosts during the sync, it looks like the difference is related to the load of the imap servers: heavy load => lower average bandwidth rate. When the load stays the same then the rate is similar.

Can you investigate a little further on your side?

An example, inverse than yours

imapsync.exe => 90.9 KiB/s
```
Transfer started at Wed Apr 18 07:51:15 2018
PID is 6572
Log file is LOG_imapsync/2018_04_18_07_51_15_167_tete@est.belle_titi.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
Load is unknown on 2 cores
Current directory is C:/Users/pc HP DV7/Desktop/imapsync_1.836/imapsync_1.836
Real user id is pc HP DV7 (uid 0)
Effective user id is pc HP DV7 (euid 0)
$RCSfile: imapsync,v $ $Revision: 1.836 $ $Date: 2017/09/05 16:14:53 $ 
Here is pcHPDV7-HP, a 3.7 GiB [MSWin32] system (Windows NT pcHPDV7-HP 6.1 Build 7601 (Service Pack 1) x86)
with Perl 5.26.0 and Mail::IMAPClient 3.39
Command line used:
C:\Users\pc HP DV7\Desktop\imapsync_1.836\imapsync_1.836\imapsync.exe --host1 p --user1 tete@est.belle --passfile1 secret.tete --host2 p --user2 titi --passfile2 secret.titi --folder INBOX.Junk.2010 --search LARGER 100000
...
Message rate                      : 0.3 messages/s
Average bandwidth rate            : 90.9 KiB/s
Reconnections to host1            : 0
Reconnections to host2            : 0
Memory consumption                : 160.5 MiB
Biggest message                   : 5850444 bytes (5.579 MiB)
Memory/biggest message ratio      : 28.8
Start difference host2 - host1    : -430 messages, -152124146 bytes (-145.077 MiB)
Final difference host2 - host1    : 0 messages, 0 bytes (0.000 KiB)
Detected 0 errors


```

perl imapsync => 141.8 KiB/s
```
Transfer started at Wed Apr 18 13:41:32 2018
PID is 8112
Log file is LOG_imapsync/2018_04_18_13_41_32_439_tete@est.belle_titi.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
Load is unknown on 2 cores
Current directory is C:/Users/pc HP DV7/Desktop/imapsync_1.836/imapsync_1.836
Real user id is pc HP DV7 (uid 0)
Effective user id is pc HP DV7 (euid 0)
$RCSfile: imapsync,v $ $Revision: 1.836 $ $Date: 2017/09/05 16:14:53 $ 
Here is pcHPDV7-HP, a 3.7 GiB [MSWin32] system (Windows NT pcHPDV7-HP 6.1 Build 7601 (Service Pack 1) amd64)
with Perl 5.26.0 and Mail::IMAPClient 3.39
Command line used:
imapsync --host1 p --user1 tete@est.belle --passfile1 secret.tete --host2 p --user2 titi --passfile2 secret.titi --folder INBOX.Junk.2010 --search LARGER 100000

...
Message rate                      : 0.4 messages/s
Average bandwidth rate            : 141.8 KiB/s
Reconnections to host1            : 0
Reconnections to host2            : 0
Memory consumption                : 193.4 MiB
Biggest message                   : 5850444 bytes (5.579 MiB)
Memory/biggest message ratio      : 34.7
Start difference host2 - host1    : -430 messages, -152124146 bytes (-145.077 MiB)
Final difference host2 - host1    : 0 messages, 0 bytes (0.000 KiB)
Detected 0 errors

```

**Comment by gilleslamiral** [comment]
No news good news! Closing
