### ISSUE TITLE
Unicode in Subject header

### ISSUE THREAD

**Issue by yuphing-ong** [imapsync/imapsync#143]
I'm using imapsync 1.882 (On Uunbut 16.04) to sync some accounts (Zimbra -> O365).

Some of the accounts have unicode subject headers, and these seem to be failing.  As example (showing some non-sensitive items):
```
Err 1/2: - msg INBOX/26791 {407558} could not append ( Subject:[=?134?Q?<ADV>_T-Shirt_for_Interior_Designers_&_Renovation_Contractors?=], Date:["05-Dec-2016 15:57:55 +0800"], Size:[407558] ) to folder INBOX: 27 BAD Command Argument Error. 11
Err 2/2: - msg INBOX/28727 {304699} could not append ( Subject:[=?134?Q?<ADV>_T-Shirts_&_Corporate_Gifts_Update_April_2017_-_ACS_Marketing?=], Date:["20-Apr-2017 07:01:15 +0800"], Size:[304699] ) to folder INBOX: 28 BAD Command Argument Error. 11

```
I checked for the latest Unicode::String (2.10) and Mail::IMAPClient (3.39) installs, but cannot get around these errors. 
These emails have graphics attached, so a bit big, but I managed to find a small (8K) message that also cannot be sync'd over: 
[Re: 蒙古项目型制作方案.eml.zip](https://github.com/imapsync/imapsync/files/2144759/Re.eml.zip)

Let me know if you need more debug information, thanks.

**Comment by gilleslamiral** [comment]
Imapsync doesn't change messages, it syncs them verbatim, no transformation is made by default.

If O365 refuse some messages, it can be anything, it may be it refuses the correct MIME encoding of the message given, it may be something else. The following header of Re:...eml.zip is ok

    Subject: Re: =?x-gbk?Q?=C3=C9=B9=C5=CF=EE=C4=BF=D0=CD=D6=C6=D7=F7=B7=BD=B0=B8?=

But the cited ones:

    =?134?Q?<ADV>_T-Shirt_for_Interior_Designers_&_Renovation_Contractors?=

are very strange since the charset 134 is unknow to me. After a little search, from https://msdn.microsoft.com/en-us/library/cc194829.aspx
 it seems charset 134 is GB2312. 

Imapsync can transform messages, changing "x-gbk" to "gbk" or "134" to "gb2312". 
But will it fix the problem? You have to investigate.

**Comment by gilleslamiral** [comment]
No news. Closing
