### ISSUE TITLE
Disable subfolder sanitization?

### ISSUE THREAD

**Issue by Thatplayer** [imapsync/imapsync#181]
I'm using imapsync to help migrate from a cPanel (Dovecot I believe) to Office365. To make this simpler I'm using the domain owner login for the cPanel account which presents all the email accounts as separate inboxes. 

This is how imapsync's list looks, the actual owner's emails: 

```
[INBOX]
[INBOX.Archive]
[INBOX.Cron]
[INBOX.Deleted Messages]
[INBOX.Drafts]
[INBOX.Junk]
[INBOX.Sent]
[INBOX.Sent Messages]
[INBOX.Trash]
```

And then the Inboxes of all the other emails on the domain: 

```
[INBOX.alex@domain_com]
[INBOX.allen@domain_com]
[INBOX.amazon@domain_com]
[INBOX.avail@domain_com]
[INBOX.jeff@domain_com]
```

When trying to select one of the inboxes with --subfolder1, the ```@``` gets sanitized:

```
Sanitizing subfolder1: [ebay@domain_com] => [ebaydomain_com]
```

This ends in an error because then it can't find the subfolder!

I've just disabled the sanitizing in the code on my end, but figured I'd file a report while it's chugging along.

**Comment by gilleslamiral** [comment]
Option --subfolder1 is not meant to select a folder, use --folderrec instead.

**Comment by gilleslamiral** [comment]
To sum up:

Sanitizing is not an option yet since it is done in the context of backup/restore with --subfolder2 first ,to backup, then also with --subfolder1 to restore, using the same string to point out the destination backup/restore folder. Reflecting on this I can see scenarios where  --subfolder1 should not sanitize, for example a restore made from a backup not done by imapsync.
Added in the TODO file.

https://imapsync.lamiral.info/TODO
````
...
SUGGESTED 2019_07_01 by Jeffrey Thatplayer
https://github.com/imapsync/imapsync/issues/181
Make sanitizing an option for --subfolder1 --subfolder2
Two options? --nosanitize1 --nosanitize2 
Reflecting more I wonder if sanitizing  for --subfolder1 is just stupid.
It's not, it's good from the usage point of view, same string to point out
the destination backup/restore folder
````

Closing this issue.
