### ISSUE TITLE
utf7 decode wrong with "+" followed by numbers in folder name

### ISSUE THREAD

**Issue by mivk** [imapsync/imapsync#187]
Folder names containing "+" are sometimes decoded as asian UTF8 characters when the "+" should actually be kept as-is.

This happens when using `Unicode::String::utf7` as in `imap_utf7_decode` : 

    echo "R&AOk-ponses 1200+1201+1202" | imap_utf7_decode
    Réponses 1200흭㗻嶴

    perl -MUnicode::String -le 'print Unicode::String::utf7("R&AOk-ponses 1200+1201+1202")->utf8'
    R&AOk-ponses 1200흭㗻嶴

 Using `Encode::IMAPUTF7` instead produces the right output:

    perl -C -MEncode::IMAPUTF7 -le 'print Encode::IMAPUTF7::decode("IMAP-UTF-7", "R&AOk-ponses 1200+1201+1202")'
    Réponses 1200+1201+1202

It is not a big problem, since the folders are created correctly on the destination. The wrong names appear only on the screen and in the logs.

(And BTW, thanks for this fantastic tool!)

**Comment by gilleslamiral** [comment]
Fixed upstream in release 1.961
Added a new dependency to Encode::IMAPUTF7
Strange thing, it has been an headache for me because one regression test was wrong so it failed with the module Encode::IMAPUTF7. For example, a folder named +BD8EQAQ1BDQEOwQ+BDM- must stay as is in imap even it is предлог in pure utf7. Took me true 3 hours to understand and acknowledge my previous misunderstanding  :-)
Not published yet but soon.
