### ISSUE TITLE
imapsync via Docker - no logs written

### ISSUE THREAD

**Issue by diteljuice** [imapsync/imapsync#189]
Hi,

I'm running imasync via Docker. On the host system neither the standard logs are written, nor the logs specified via --logfile. Couldn't find the logs in the container too.

do_imap_migration.sh:
```bash
echo Looping on account credentials found in file.txt
echo

while test $# -gt 0; do
        case "$1" in
                --dry|-n)
                        dry_run='--dry'
                        shift
                        ;;
                *)
                        break
                        ;;
        esac
done

{ while IFS=';' read  h1 u1 p1 e1 h2 u2 p2 e2 fake
    do
        case $e1 in
          tls)
            crypt1='--tls1'
            ;;
          ssl)
            crypt1='--ssl1'
            ;;
          *)
            crypt1='--nossl1 --notls1'
        esac
        case $e2 in
          tls)
            crypt2='--tls2'
            ;;
          ssl)
            crypt2='--ssl2'
            ;;
          *)
            crypt2='--nossl2 --notls2'
        esac
        { echo "$h1" | tr -d '\r' | egrep '^#|^ *$' ; } > /dev/null && continue # this skip commented lines in imap_accounts_to_migrate.txt
        echo "==== Starting imapsync from host1 $h1 user1 $u1 using encryption $crypt1 to host2 $h2 user2 $u2 using encryption $crypt2 ===="
        NOW=$(date +"%y%m%d_%R:%S")
        docker run gilleslamiral/imapsync imapsync $dry_run --logfile "LOGS/log_$u1_$NOW.txt" --host1 "$h1" --user1 "$u1" --password1 "$p1" $crypt1 \
                 --host2 "$h2" --user2 "$u2" --password2 "$p2" $crypt2 \
                 "$@" #\
                 #> LOGS/log_${u2}_$NOW.txt 2>&1
        echo "==== Ended imapsync from host1 $h1 user1 $u1 using encryption $crypt1 to host2 $h2 user2 $u2 using encryption $crypt2 ===="
        echo
    done
} < imap_accounts_to_migrate.txt
```

Benjamin

**Comment by gilleslamiral** [comment]
As far as I understand Docker, a docker run can't change or create files outside the container. A docker run doesn't change the image container as well, the image container stays the same. Am I wrong?

**Comment by diteljuice** [comment]
You are right! I thought it's possible to mount a local path in the Dockerfile, but it isn't. 
So the local volume has to be mounted on `docker run -v /local_path/:/docker_path/` What is the path to the log files in the container?

**Comment by gilleslamiral** [comment]
Imapsync disables logging in docker context, because it is useless.

If your goal is to get a log file of a run, just remove the commented code on the shell script `do_imap_migration.sh` above like:
````
docker run gilleslamiral/imapsync imapsync --host1 "$h1" --user1 "$u1" --password1 "$p1" \
                 --host2 "$h2" --user2 "$u2" --password2 "$p2"  \
                 "$@" > LOGS/log_${u2}_$NOW.txt 2>&1
````

By the way, there is no need to deal the script parameters  like it is written above. Without the first "while loop" that removes all parameters to search but the --dry one, a run of the script like this:

     do_imap_migration.sh --dry --blabla --whatever

would run imapsync like this:

     docker run gilleslamiral/imapsync imapsync ... --dry --blabla --whatever

because of the "$@" variable that means "all parameters of this script, well quoted".

Another useless treatment are the $e1 and $e2 variables. You could put all supplementary  parameters in the `imap_accounts_to_migrate.txt` in the last column. All those parameters will go in the $fake variable so changing the call to

    docker run gilleslamiral/imapsync imapsync ... $fake

will take a line like:

    test1.lamiral.info;test1;secret1;test2.lamiral.info;test2;secret2;--ssl1 --tls2 --automap;

and run:

    docker run gilleslamiral/imapsync imapsync ... --ssl1 --tls2 --automap

because `$fake` variable will then contain `--ssl1 --tls2 --automap`

**Comment by diteljuice** [comment]
Thanks for the support. :) I will have a look at the bash script.

Changing `> LOGS/log_${u2}_$NOW.txt 2>&1` to `2>&1 | tee LOGS/log_${u2}_$NOW.txt` will print the progress on screen and write the logfile.
