### ISSUE TITLE
Folders getting deleted with --delete1emptyfolders even when they have subfolders with mails

### ISSUE THREAD

**Issue by pazzero** [imapsync/imapsync#207]
If you use the option `--delete1emptyfolders` and have the following folderstructure in your INBOX  the Subfolder 1 and the Subfolder 1.1 and 2.1 get's deleted before they are synced:

INBOX   (999 Mails synced)
INBOX/Subfolder1   (**0 Mails** deleted while syncing)
INBOX/Subfolder1/Subfolder1.1   (100 Mails deleted before get synced)
INBOX/Subfolder2/Subfolder2.1   (50 Mails deleted before get synced)

This option should be more advanced to delete empty folders when all subfolders are also empty.

**Comment by gilleslamiral** [comment]
This behavior is very unlikely! The option code is written to avoid deleting folders with subfolders since a folder with subfolders is not empty at all. Now the question becomes why it does it regardless of the precaution. 
Can you run it like
`imapsync ... --dry --justfolders --delete1emptyfolders --debugimap1` 
and send me the log?

**Comment by pazzero** [comment]
I've created an examplefolderstructure to show the behavior while syncing. Here is the part of the logfile where the empty topfolder is beeing deleted by imapsync:

```
,Host1 deleting empty folders
,Host1: folder INBOX/Emptyfolder/Subfolder2 has messages: 6 (search) 6 (select)
,Host1: folder INBOX/Emptyfolder/Subfolder1 has messages: 4 (search) 4 (select)
,Host1: deleting empty folder INBOX/Emptyfolder
,Host1 deleted INBOX/Emptyfolder
,Host1 ended deleting empty folders
,++++ Looping on each one of 2 folders to sync
,Folder     1/2 [INBOX/Emptyfolder/Subfolder1]      -> [INBOX.Emptyfolder.Subfolder1]     
,Host1: folder [INBOX/Emptyfolder/Subfolder1] has 4 messages in total (mentioned by SELECT)
,Host2: folder [INBOX.Emptyfolder.Subfolder1] has 0 messages in total (mentioned by SELECT)
,Host2: folder [INBOX.Emptyfolder.Subfolder1] permanentflags: 
,Host1: Expunging INBOX/Emptyfolder/Subfolder1 
,Host1: folder [INBOX/Emptyfolder/Subfolder1] considering 0 messages
,Host2: folder [INBOX.Emptyfolder.Subfolder1] considering 0 messages
,Host1: folder [INBOX/Emptyfolder/Subfolder1] selected 0 messages, duplicates 0
,Host2: folder [INBOX.Emptyfolder.Subfolder1] selected 0 messages, duplicates 0
,Host1: Expunging folder INBOX/Emptyfolder/Subfolder1 
,Folder     2/2 [INBOX/Emptyfolder/Subfolder2]      -> [INBOX.Emptyfolder.Subfolder2]     
,Host1: folder [INBOX/Emptyfolder/Subfolder2] has 6 messages in total (mentioned by SELECT)
,Creating folder [INBOX.Emptyfolder.Subfolder2] on host2
,Created folder [INBOX.Emptyfolder.Subfolder2] on host2
,Host2: folder [INBOX.Emptyfolder.Subfolder2] has 0 messages in total (mentioned by SELECT)
,Host2: folder [INBOX.Emptyfolder.Subfolder2] permanentflags: 
,Host1: Expunging INBOX/Emptyfolder/Subfolder2 
,Host1: folder [INBOX/Emptyfolder/Subfolder2] considering 0 messages
,Host2: folder [INBOX.Emptyfolder.Subfolder2] considering 0 messages
,Host1: folder [INBOX/Emptyfolder/Subfolder2] selected 0 messages, duplicates 0
,Host2: folder [INBOX.Emptyfolder.Subfolder2] selected 0 messages, duplicates 0
,Host1: Expunging folder INBOX/Emptyfolder/Subfolder2 
,++++ End looping on each folder
,Host1 deleting empty folders
,Host1 folder INBOX/Emptyfolder/Subfolder2: Could not examine: 35 NO EXAMINE could not open 'INBOX/Emptyfolder/Subfolder2', reason 1081
,Host1 folder INBOX/Emptyfolder/Subfolder1: Could not examine: 37 NO EXAMINE could not open 'INBOX/Emptyfolder/Subfolder1', reason 1081
,Host1 ended deleting empty folders
```

The result ist that no messeges get synced to Host2:

```
,Messages transferred                    : 0 
,Messages skipped                        : 0
```

I try to migrate from FirstClass to Dovecot and in a second step to exchange. The direct sync to exchange produces to much errors.

**Comment by gilleslamiral** [comment]
Can you do the same run with:

     imapsync ... --dry --justfolders --delete1emptyfolders --debugimap1

and send me the log?

**Comment by gilleslamiral** [comment]
Thanks for the log I asked.
Now the explanation of the behavior. The imap server says contradictory claims about 
children of "INBOX/Emptyfolder".

During the initial folder list, the imap server is right:
````
,Sending: 12 LIST "" *
...
,Read:  * LIST (\Unmarked \HasChildren) "/" "INBOX/Emptyfolder"
,Read:  * LIST (\Unmarked \HasNoChildren) "/" "INBOX/Emptyfolder/Subfolder1"
````
then later, during the delete1emptyfolders() execution, the imap server is plainly wrong,
it says "INBOX/Emptyfolder" \HasNoChildren:
````
,Sending: 20 LIST "" INBOX/Emptyfolder
,Sent 30 bytes
,Read:  * LIST (\Unmarked \HasNoChildren) "/" "INBOX/Emptyfolder"
,Read:  20 OK LIST completed
````
It looks like you found a bug in FirstClass.

**Comment by pazzero** [comment]
Thank you very much for reviewing my log and your support!!! It's not the only bug in FirstClass... one of the reasons why we're changing to Exchange!

**Comment by gilleslamiral** [comment]
Ok. I've updated 
https://imapsync.lamiral.info/FAQ.d/FAQ.Various_Software_Servers.txt
...
Q. From FirstClass to XXX
   http://www.firstclass.com/

R. Migrating from FirstClass is not easy because FirstClass, strangely, 
   does not show all messages via IMAP. To make it show all messages,
   a trick, painful to follow by hand, is moving emails 
   out and back in, for each folder. May be it can be done by a script.

  FirstClass releases prior to release 12 do not shows the "Sent" 
  folder in IMAP but FirstClass release 12 shows it.
  I advice you to upgrade to FirstClass release 12 before leaving it
  with imapsync or another imap tool.

See also this worth reading discussion in a Zimbra forum:
https://web.archive.org/web/20120627043731/http://www.zimbra.com/forums/migration/20349-help-needed-migrating-firstclass.html

Another advice with FirstClass as host1, do not use --delete1emptyfolders since
it will destroy all subfolders of any empty folder. This is a FirstClass bug:
when asked to list a non-empty folder it says it has no children while it does
have ones.
See the details and explanations at
https://github.com/imapsync/imapsync/issues/207
````
