### ISSUE TITLE
UTF7 to UTF8 decoding bugs

### ISSUE THREAD

**Issue by Hubbitus** [imapsync/imapsync#23]
Firstly there bug and you by some reason exclude + sign from utf7 string which leads to its mangle. For example in Russian language word project is "проект" what in UTF7-IMAP encoding represent as "&BB8EQAQ+BDUEOgRC-" but imapsync decode it as "ПроBDUEOgRC-"

I have breaffy look at code and by some reason you are especially leave + sign in imap_utf7_decode routine:
```perl
sub imap_utf7_decode {
        $s =~ s/\+/PLUSPLACEHOLDER/g ;
        $s =~ s/&([^,&\-]*),([^,\-&]*)\-/&$1\/$2\-/g ;
        $s =~ s/&(?!\-)/\+/g ;
        $s =~ s/&\-/&/g ;
        $s =~ s/PLUSPLACEHOLDER/+-/g ;

        return( Unicode::String::utf7( $s )->utf8 ) ;
}
```

Additionally I want mention, despite *some* folder names decoded, in many place except folders list it present as is, for example:
```
Excluding folders matching pattern 'BAK_test/Ant/INBOX': [BAK_test/Ant/INBOX/&BB8EQAQ+BDEEOwQ1BDwESw- &BD8EPg- &BD4EQgRHBFEEQgQwBDw- &BEEEQAQwBDIEPQQ1BD0EOARP-] [BAK_test/Ant/INBOX/TODO] [BAK_test/
Ant/INBOX/TODO-ANSWER] [BAK_test/Ant/INBOX/TODO/Answer - &BCEEPgQxBD4EOwQ1BDI-]
…
```

**Comment by gilleslamiral** [comment]
Dear Pavel,

You're definitively right. This 10 years old bug is also mentioned at:
https://rt.cpan.org/Public/Bug/Display.html?id=11172
which seem to have led to writing a new one
http://search.cpan.org/~pmakholm/Encode-IMAPUTF7-1.05/lib/Encode/IMAPUTF7.pm

The fix is easy, remove the two lines containing PLUSPLACEHOLDER

# Copied from http://cpansearch.perl.org/src/FABPOT/Unicode-IMAPUtf7-2.01/lib/Unicode/IMAPUtf7.pm
# and then fixed with
# https://rt.cpan.org/Public/Bug/Display.html?id=11172
sub imap_utf7_decode {
         my ( $s ) = shift( @_ ) ;

         # Algorithm
         # On remplace , par / dans les BASE 64 (, entre & et -)
         # On remplace les &, non suivi d'un - par +
         # On remplace les &- par &
         $s =~ s/&([^,&\-]*),([^,\-&]*)\-/&$1\/$2\-/g ;
         $s =~ s/&(?!\-)/\+/g ;
         $s =~ s/&\-/&/g ;
         return( Unicode::String::utf7( $s )->utf8 ) ;
}

This bugfix will be applied in next public release.


Le 17/01/2015 12:13, Pavel Alexeev aka Pahan-Hubbitus a écrit :
> Firstly there bug and you by some reason exclude + sign from utf7 string which leads to its mangle. For example in Russian language word project is "проект" what in UTF7-IMAP encoding represent as "&BB8EQAQ+BDUEOgRC-" but imapsync decode it as "ПроBDUEOgRC-"
>
> I have breaffy look at code and by some reason you are especially leave + sign in imap_utf7_decode routine:
>
> sub  imap_utf7_decode  {
>          $s  =~s/\+/PLUSPLACEHOLDER/g  ;
>          $s  =~s/&([^,&\-]*),([^,\-&]*)\-/&$1\/$2\-/g  ;
>          $s  =~s/&(?!\-)/\+/g  ;
>          $s  =~s/&\-/&/g  ;
>          $s  =~s/PLUSPLACEHOLDER/+-/g  ;
>
>          return( Unicode::String::utf7($s  )->utf8 ) ;
> }
>
> Additionally I want mention, despite /some/ folder names decoded, in many place except folders list it present as is, for example:
>
> |Excluding folders matching pattern 'BAK_test/Ant/INBOX': [BAK_test/Ant/INBOX/&BB8EQAQ+BDEEOwQ1BDwESw- &BD8EPg- &BD4EQgRHBFEEQgQwBDw- &BEEEQAQwBDIEPQQ1BD0EOARP-] [BAK_test/Ant/INBOX/TODO] [BAK_test/
> Ant/INBOX/TODO-ANSWER] [BAK_test/Ant/INBOX/TODO/Answer - &BCEEPgQxBD4EOwQ1BDI-]
> …
> |
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/23>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
