### ISSUE TITLE
Compare duplicates only by headers is buggy

### ISSUE THREAD

**Issue by Hubbitus** [imapsync/imapsync#24]
I have two messages (full source, address mangled):
```
From: admin@domain.tld
Subject: quota warning

Your mailbox is now below% full.
```
and
```
From: admin@domain.tld
Subject: quota warning

Your mailbox is now 80% full.
```

When I sync directory with they by imapsync 1.607 I got:
```
++++ End looping on each folder
++++ Calculating sizes on Host1
Host1 folder [BAK_test/Ant/Archives/2014]        Size:     18371 Messages:     7 Biggest:     10827
Host1 Nb messages:               7 messages
…
++++ Calculating sizes on Host2
Host2 folder [BAK/Ant/Archives/2014]             Size:     18280 Messages:     6 Biggest:     10827
Host2 Nb messages:               6 messages
…
++++ Statistics
Transfer started on               : Sat Jan 17 21:10:21 2015
Transfer ended on                 : Sat Jan 17 21:10:32 2015
Transfer time                     : 11.0 sec
Messages transferred              : 0
Messages skipped                  : 7
Messages found duplicate on host1 : 1
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 0
Messages void (noheader) on host2 : 0
Messages deleted on host1         : 0
Messages deleted on host2         : 0
…
Initial difference host2 - host1  : -1 messages, -91 bytes (-0.089 KiB)
Final   difference host2 - host1  : -1 messages, -91 bytes (-0.089 KiB)
```

**So, they are treated as duplicates which are not! It seems as bug for me**.
It will be good to see compare full mail byte-to-byte before threat as duplicates. Or at least such option.

In sync options --useheader ALL --addheader used, so I do not see how I could make compare strictly.

Use UIDs seams as possibility there, but I do not want depends on cache present.

**Comment by gilleslamiral** [comment]
Dear Pavel,

> I have two messages (full source, address mangled):
>
> |From: admin@domain.tld
> Subject: quota warning
>
> Your mailbox is now below% full.
> |
>
> and
>
> |From: admin@domain.tld
> Subject: quota warning
>
> Your mailbox is now 80% full.
> |

> When I sync directory with they by imapsync 1.607 I got:

> Messages found duplicate on host1 : 1
>
> *So, they are treated as duplicates which are not! It seems as bug for me*.

My idiot point of view: Those messages are not RFC 5322 compliant,
they lacks the "Date:" header field. They are the bug, fix them.

> It will be good to see compare full mail byte-to-byte before threat as duplicates.

It would be very bad for 99.9999% of imap migrations.
Even --useheader ALL is very often a bad criterion since it generates duplicates,
the reverse issue of yours. Combination "--useheader ALL --noskipsize" was the
default behavior in the early releases of imapsync, I had to change this
default very soon, it doesn't work most of the time, too few imap servers
respect messages, headers are changed, the size too.

 > Or at least such option.

Feel free to code it.
I can already tell you I won't add that patch.
What happens to you comes from "fake" messages, messages that had never seen
any SMTP server of their entire life, messages generated and put directly
in a mailbox without any software that knows the basics of email.

> In sync options --useheader ALL --addheader used, so I do not see how I could make compare strictly.

Use:

   imapsync ... --noskipsize

It should be enough to fix this issue.

> Use UIDs seams as possibility there, but I do not want depends on cache present.

It looks like you don't want to solve this issue easily.


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by Hubbitus** [comment]
> My idiot point of view: Those messages are not RFC 5322 compliant, they lacks the "Date:" header field. They are the bug, fix them.

If there will Date header and they equals? But I agree it may made such problem not so serious.

Thank you for --noskipsize hit, I'll try. In that particular case it should help (but for example 90% and 80% in text make messages equals by length too).

> It looks like you don't want to solve this issue easily.
Why you think so?

**Comment by gilleslamiral** [comment]
Dear Pavel,

>     My idiot point of view: Those messages are not RFC 5322 compliant, they lacks the "Date:" header field. They are the bug, fix them.
>
> If there will Date header and they equals? But I agree it may made such problem not so serious.

If you fix this issue by setting the same Date: header then the bug is moved to you
and you have to be fixed as well.

> Thank you for --noskipsize hit, I'll try. In that particular case it should help
 > (but for example 90% and 80% in text make messages equals by length too).

Yes. --useuid is THE solution for your kind of mind.

>     It looks like you don't want to solve this issue easily.
>     Why you think so?

Because you refuse --useuid solution, which is an easy solution.

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by Hubbitus** [comment]
Help said about --useuid: "Caveat: --useuid --nousecache creates duplicates on multiple runs.". I assume If I just delete some time cache and rerun it will lead to equivalent results, is not?

**Comment by gilleslamiral** [comment]
Dear Pavel,

> Help said about --useuid: "Caveat: --useuid --nousecache creates duplicates on multiple runs.".
 > I assume If I just delete some time cache and rerun it will lead to equivalent results, is not?

Yes. Deleting the cache make --useuid generates duplicates.
It can be regenerated at any time with --usecache and without --nouseuid.

Every imap email software in the universe has a cache by default, except imapsync.
What's the problem with having a uid cache?


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
