### ISSUE TITLE
Debian 10.6 Docker container - script calls itself (?)

### ISSUE THREAD

**Issue by bryanpedini** [imapsync/imapsync#249]
Too many dependencies and an unknown software (for now) - perfect recipe for computer disruption (just kidding, I hope).

However, when from a security standpoint, Docker does a great job of isolating things, it appears that `imapsync` doesn't like it that much... (I even needed to download more packages after running `sh INSTALL.d/prerequisites_imapsync`)
```
Can't open ./imapsync: No such file or directory at ./imapsync line 16214.
```

Dockerfile used, if helpful: [Dockerfile.txt](https://github.com/imapsync/imapsync/files/5543760/Dockerfile.txt) - remove `.txt` (stupid GitHub)...

**Comment by bryanpedini** [comment]
Tried brand new virtual machine with same Debian version (10.6.0) and it works fine with all the packages copied from the Dockerfile.
Clearly there is some requirement missing in the base Debian container image that's already present when installing via ISO.

**Comment by gilleslamiral** [comment]
I don't understand what you have done in both messages. 

1) For the first, it looks like you tried to build your own imapsync Docker image and failed. Have you done something like:

   docker build -t gilleslamiral/imapsync . 

like explained at https://hub.docker.com/r/gilleslamiral/imapsync/
This build can be done on any system, any Unix, any Mac, any Windows, as long as they have Docker running.

2) For the second post, it looks you installed imapsync on a "native", virtual, Debian 10. The document to do it is not the Docker one, it is preferable to use https://imapsync.lamiral.info/INSTALL.d/INSTALL.Debian.txt

**Comment by bryanpedini** [comment]
Oh, so you have a Docker image going on... I see now `Dockerfile` is in `INSTALL.d`, I looked under the root directory of the repo only and was going to build one myself from scratch, yes. 😅

Anyway, "native", virtual, Debian 10, doesn't work on Docker, does work on a VM with the same packages installed; that's why I asked.
Tho if an official image is maintained, updated, and already available, why would I need to build another one then? 😬

**Comment by gilleslamiral** [comment]
Ok, now I understand what you tried to do, building an imapsync Docker image from scratch.

I also understand the issue you encountered.

Imapsync 1.977 doesn't call itself at line 16214 but it reads itself in order to generate the usage output. 
The README and the `--help` output documentation is embedded in imapsync itself, at the top.

> Tho if an official image is maintained, updated, and already available, why would I need to build another one then?

Sure!

Googling "imapsync docker" would have gave you this solution right away.
It still happens every day to me, why don't I start googling my problems first?

**Comment by bryanpedini** [comment]
> It still happens every day to me, why don't I start googling my problems first?

Because with latest updates Google has become more commercial and bullshit-useless than ever.
Nowadays it doesn't find any good result for technicalities, only if you search a brand name, a product, or in general have money to spend in what Google suggests you...
That's why 😉

Anyway, thank you for your help Gilles!!
Have a nice day, and stay safe.
Close the issue if you want, I see Docker is not the best solution to actually `build` the software...

**Comment by gilleslamiral** [comment]
Technically speaking, Imapsync is built by default since it's a Perl script, the binary build is done at every run, that's the Perl way.
Many installations, including docker, are documented at https://imapsync.lamiral.info/#install

I still find Google very pertinent on technical questions or on any query. Show me a good page on a subject that is not top presented by Google. 

Also, Ctrl-f docker on the imapsync home page gives the docker build link. Historically I planned to put all the documentation, FAQs, README etc. in a single page. Because Ctrl-f is my friend forever :-)
 
I close the issue, you can still reply, closed issues stay open, closed is just a tag.
