### ISSUE TITLE
disable email notification from help@imapsync.tk

### ISSUE THREAD

**Issue by mazaamahesh** [imapsync/imapsync#341]
HI,

how can I disable the email notification from the email id help@imapsync.tk

Imapsync just ended the synchronization from the imap account user@domain.com to the imap account user@domain.com.

**Comment by mazaamahesh** [comment]
HI,

Thanks for the solution. is there any way to Add options --noemailreport1 and --noemailreport2 On by default?

**Comment by florenthemmi** [comment]
By default it is: `--emailreport1 and --emailreport2`.
Ping @gilleslamiral

**Comment by gilleslamiral** [comment]
Near line 1540, replace

```
$sync->{ emailreport1 } = defined $sync->{ emailreport1 } ? $sync->{ emailreport1 } :  1 ;
$sync->{ emailreport2 } = defined $sync->{ emailreport2 } ? $sync->{ emailreport2 } :  1 ;
```
by
```
$sync->{ emailreport1 } = defined $sync->{ emailreport1 } ? $sync->{ emailreport1 } :  0 ;
$sync->{ emailreport2 } = defined $sync->{ emailreport2 } ? $sync->{ emailreport2 } :  0 ;
```

**Comment by thomergil** [comment]
Respectfully, for backwards compatibility, I think the default should be off. I assume (perhaps falsely) that most people run imapsync from cron: it's unexpected and undesirable to start receiving emails every few minutes/hours/days after an imapsync upgrade.

**Comment by gilleslamiral** [comment]
Next public release will turn off the email reports, they bother me more than anyone else.

**Comment by kosli** [comment]
@gilleslamiral  thank you!
btw, the options are missing in the command line help and README file -> luckily I found the issue here and was able to disable it :-)

**Comment by SVerkuil** [comment]
Gilles, first of all, thanks for this excellent piece of software, works perfectly.

Regarding this issue. I tried running a test transfer with `--dry` (dry-run). However, after the dry run completed, the imapsync mail notification was still put in both the source and destination mailbox.

I would expect when running with `--dry --emailreport1 --emailreport2` still nothing actually happens with the mail boxes, since it is a dry run, so in this case `--dry` should in my opinion force equivalent behavior of `--noemailreport1 --noemailreport2`.

**Comment by kosli** [comment]
Thanks @SVerkuil, that is exactly how i discovered the "emailreport" feature.... I run the sync in dry-mode and was surprised seeing a new message in the mailboxes.. especially a "fake" message ;-)
