### ISSUE TITLE
duplication when using addheader option

### ISSUE THREAD

**Issue by trlthiago** [imapsync/imapsync#351]
Hi, 

I am getting message duplication when using `--addheader`. 

For testing I used the `--useheader` with a nonexistent header to force `--addheader` being applied.

I've executed the following command line multiple times, and all trial transfered the same message creating the duplication.

`imapsync.exe [...] --addheader --useheader test --debugimap`

On destination all duplicated messages got the same Message-Id:
`Message-Id --> <1@imapsync>`

The behaviour seems `addheader` skips the comparison and always make the transfer.

I hoped that imapsync check on destination if already exists an `1@imapsync` before the transfer.

Is it the expected behaviour or it could be changed? or should I add another option to complement ?

Thanks in advance.

**Comment by gilleslamiral** [comment]
--addheader adds a "Message-ID:" header, not a "test:" header.

With `--useheader test`, imapsync uses the "test:" header to identify messages. So it doesn't use Message-ID header because it is told not to. 

 Forcing --addheader to be applied is a bad idea because you end up with messages with several Message-ID, some equal, some different.

What is your initial issue? What makes you try this solution?

**Comment by gilleslamiral** [comment]
--addheader adds a "Message-ID:" header, not a "test:" header.

With `--useheader test`, imapsync uses the "test:" header to identify messages. So it doesn't use Message-ID header because it is told not to. 

 Forcing --addheader to be applied is a bad idea because you end up with messages with several Message-ID, some equal, some different.

What is your initial issue? What makes you try this solution?
