### ISSUE TITLE
"Use of uninitialized value $sockargs[11]" and "Connection reset by peer"

### ISSUE THREAD

**Issue by loumatzer** [imapsync/imapsync#59]
Hi,

by first thanks for this awesome tool! :+1: 

Since a few days we're getting alot of these errors.
Sometimes it's $sockargs[11] and sometimes it's $sockargs[13] and so on.

We want to migrate quite a big imap-account to Exchange. (Right aroung 10GiB)

Have you seen these errors before?

Thanks for your help!

Greetings,
Louis

**Comment by gilleslamiral** [comment]
Hi Louis,

Can you send me a whole log?

> Hi,
> 
> by first thanks for this awesome tool! :+1:
> 
> Since a few days we're getting alot of these errors.
> Sometimes it's $sockargs[11] and sometimes it's $sockargs[13] and so on.
> 
> We want to migrate quite a big imap-account to Exchange. (Right aroung
> 10GiB)
> 
> Have you seen these errors before?
> 
> Thanks for your help!
> 
> Greetings,
> Louis
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/imapsync/imapsync/issues/59>.
> 

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by maniargaurav** [comment]
Following is Log that I can provide you. Please help me to fix the issue:

Modules version list:
Mail::IMAPClient     3.37
IO::Socket           1.31
IO::Socket::IP       ?
IO::Socket::INET     1.31
IO::Socket::SSL      1.31
Net::SSLeay          1.35
Compress::Zlib       2.021
Digest::MD5          2.39
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.01
Term::ReadKey        2.30
File::Spec           3.3
Time::HiRes          1.9721
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON                 ?
JSON::WebToken       ?
Crypt::OpenSSL::RSA  ?
LWP                  6.15
HTML::Entities       3.64
Filesys::DfPortable  ?
( use --no-modules_version to turn off printing this Perl modules list )
Use --sslargs2 SSL_verify_mode=1 for SSL_VERIFY_PEER on host2
ssl debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connexion timeout is 120 seconds
Host2: imap connexion timeout is 120 seconds
Host1: IMAP server [192.168.13.250] port [143] user [XXX@XXX.com]
Host2: IMAP server [imap.gmail.com] port [993] user [XXX@XXX.com]
Host1: connecting and login on host1 [192.168.13.250] port [143] with user [XXX@XXX.com]
Host1 banner: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=CRAM-MD5] Dovecot ready(4)
Host1: 192.168.13.250 says it has CAPABILITY for AUTHENTICATE LOGIN
Host1: success login on [192.168.13.250] with user [XXX@XXX.com] auth [LOGIN]
Host2: connecting and login on host2 [imap.gmail.com] port [993] with user [XXX@XXX.com]
Use of uninitialized value $sockargs[9] in join or string at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 360.
Use of uninitialized value $fam_listen in numeric ne (!=) at /usr/share/perl5/IO/Socket/INET6.pm line 226.

**Comment by gilleslamiral** [comment]
Hi Gaurav,

I don't see "Can not open imap connection on [imap.gmail.com]",
no complete log, but it looks like it
http://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt

=======================================================================
Q. Can not open imap connection on [imap.gmail.com]:
    Unable to connect to imap.gmail.com

R0. It looks like this issue is related to ipv6. Both ipv4 and ipv6
protocols should work with gmail and imapsync, I test that regularly,
imapsync works fine for both ipv4 and ipv6.
If you disable ipv6 then disable also ipv6 resolution!
Or at least, make ipv4 answers be taken before ipv6 since the default
names resolution order is to present ipv6 name resolutions first.

R1. A first simple solution is to use directly gmail ipv4 ip address:

   imapsync ... --host1 64.233.184.108

In case it changes, get it with any command showing the imap.gmail.com
name resolution, try one of those:

   nslookup imap.gmail.com
   host     imap.gmail.com
   ping     imap.gmail.com

Or go to http://ping.eu/nslookup/ to get the resolution.

R2. Second solution. Fix imapsync with the line:

   use IO::Socket::SSL 'inet4' ;

Thanks to Chris Nolan to report, understand and fix this issue!

=======================================================================

Le 02/03/2016 14:08, Gaurav Maniar a écrit :
> Following is Log that I can provide you. Please help me to fix the issue:

> Host2: connecting and login on host2 [imap.gmail.com] port [993] with user [XXX@XXX.com <mailto:XXX@XXX.com>]
> Use of uninitialized value $sockargs[9] in join or string at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 360.
> Use of uninitialized value $fam_listen in numeric ne (!=) at /usr/share/perl5/IO/Socket/INET6.pm line 226.


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
