### ISSUE TITLE
Feature proposal: attachment handling

### ISSUE THREAD

**Issue by raimocom** [imapsync/imapsync#78]
I propose the following extra functionality:
1. `imapsync --dontsyncattachments`
   only sync the text part of the message, omit all attachments
2. `imapsync --saveattachments /folder/to/save/attachments`
   save attachments to specified folder. Add uniqe token (message-id, hash, etc)  to filename to avoid naming clashes (flower.jpg -> flower_z12bd19794db.jpg)
3. `imapsync --addattachmenturl http://my.server/folder/of/saved/attachments`
   add specified URL + generated attachment filename to the bottom of the message.
   Example:
   _Attachments of this message have been stripped. Attached files can be found here:
   http://my.server/folder/of/saved/attachments/flower_z12bd19794db.jpg_

That would be helpful for transferring mails to a (local network) archival IMAP server. Your thoughts, Gilles?

Raimo

**Comment by gilleslamiral** [comment]
Hi Raimo,

Nice idea, it will surely help when the destination server host2 restricts
messages sizes to a smaller value than the source server host1.

But this nice idea has to be coded.

If you know a command, let's call it "attachtool", written in any language, that does this
- takes a message as input (stdin)
- does any of your suggestions, directed by options, like --saveattachments /folder/to/save/attachments or --addattachmenturl http://my.server/folder/of/saved/attachments
- prints the result message as output (stdout)
then imapsync can already use it with --pipemess:

   imapsync ...  --pipemess "attachtool --addattachmenturl http://my.server/folder/of/saved/attachments"

But I don't think it's a nice idea for an archival IMAP server,
an archival IMAP server has to keep all messages as they are.
Why? because archiving is for restoring or seeing again via email software,
the simplest and best way to this need is to not touch messages at all.
Seeing most attachments via a web browser won't be user friendly, it's just text encoded files,
so this solution, separate attachments, implies more tools to be really usable.

I prefer the following solution:
use a decent destination IMAP server that allows bigger messages than the previous one.

Le 20/09/2016 à 23:42, raimocom a écrit :
> I propose the following extra functionality:
>
>  1.
>
>     |imapsync --dontsyncattachments|
>     only sync the text part of the message, omit all attachments
>
>  2.
>
>     |imapsync --saveattachments /folder/to/save/attachments|
>     save attachments to specified folder. Add uniqe token (message-id, hash, etc) to filename to avoid naming clashes (flower.jpg -> flower_z12bd19794db.jpg)
>
>  3.
>
>     |imapsync --addattachmenturl http://my.server/folder/of/saved/attachments|
>     add specified URL + generated attachment filename to the bottom of the message.
>     Example:
>     /Attachments of this message have been stripped. Attached files can be found here:
>     http://my.server/folder/of/saved/attachments/flower_z12bd19794db.jpg/
>
> That would be helpful for transferring mails to a (local network) archival IMAP server. Your thoughts, Gilles?
>
> Raimo


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by gilleslamiral** [comment]
I don't plan to code that.

**Comment by DaniW42** [comment]
Wouldn't it be an idea to simply skip attachments? So people could fully sync mails like, from the past six years and sync mails older than six years without attachment.

**Comment by gilleslamiral** [comment]
What is already possible with imapsync:

- Avoid to sync messages by size  (1MB here) with ` --maxsize 1000000`
- Avoid to sync messages by date (6 years here, 366*6=2196) with ` --maxage 2196` or ` --search "SENTSINCE 1-Jan-2014" `
- Truncate messages under a size (1MB here) with ` --truncmess 1000000`
- A combinaison of the above, among all the others: https://imapsync.lamiral.info/FAQ.d/FAQ.Messages_Selection.txt

I consider it far enough for most needs about skipping old big messages.

If you like to argue, what's the point to remove old attachments only? 
How do you know attachments are not important, less important than the message itself? 
Is it because they're old?

Talking about the technical part of the suggestion; nowadays, mostly every message is an attachment by itself, using Mime. The message I received from you from github is written as 2 "attachments". Headache assured for the implementation.

Two years later I still don't plan to code that.

**Comment by plutocrat** [comment]
There are a couple of tools that spring to mind which might work. 
ripmime        https://github.com/inflex
altermime     http://pldaniels.com/altermime/
mimedefang      https://mimedefang.org/
I've been looking at these for another project, but thought they might be useful here.

**Comment by gilleslamiral** [comment]
> There are a couple of tools that spring to mind which might work.
> ripmime https://github.com/inflex

Looking at the six projects, the only one related to emails seems to be:
https://github.com/inflex/ripMIME

I don't see any example. the Usage section is void.
Does it take an email message RFC2822 as input on stdin? 
What does it give on stdout?

> altermime http://pldaniels.com/altermime/

I see no example of how to use it, stdin/stdout?

> mimedefang https://mimedefang.org/

I read the documentation (pdf) and I don't see how mimedefang could be used by imapsync.

> I've been looking at these for another project, but thought they might be useful here.

Can you describe how they might be useful with imapsync?

**Comment by plutocrat** [comment]
I agree the documentation leaves something to be desired! Once you install the programs, running them gives usage instructions. 
As far as I gathered, something like this should work. 
`cat excel.eml | altermime --removeall --input=- > excel.out`
And indeed it did seem to be working in my initial tests. But then I ran into a roadblock with something else and then abandoned the project. 
[altermime_usage.txt](https://github.com/imapsync/imapsync/files/6588805/altermime_usage.txt)
[ripmime_usage.txt](https://github.com/imapsync/imapsync/files/6588808/ripmime_usage.txt)

**Comment by gilleslamiral** [comment]
Thanks for your input plutocrat! 
You showed that the tools altermime and ripmime can use stdin and stdout, the Unix way, so they're already usable with imapsync via the option --pipemess; that's great news!
