### ISSUE TITLE
Special Character § in the Password -> NO LOGIN failed

### ISSUE THREAD

**Issue by Fvbor** [imapsync/imapsync#85]
Hi and a happy new year!

In the last days I´ve tested imapsync a little bit and detected a little bug.
host2 is an Exchange server, Login is possible with a lot of other user/passwords
imapsync in the latest version on Windows 7 x64 (Ger)

In one of the passwords is a § Sign.
For this, as example: The password is: Test§Test

But I´ve got only "NO LOGIN failed" with this password.
Tested: (And with 0167, A7 as ASCII code for the §)
--password2 "Test§Test"
--password2 Test§Test
--password2 "Test^§Test"
--password2 Test^§Test
--password2 "Test\§Test"
--password2 Test\§Test
--password2 Test\§Test

After a quick look into the packet trace I´ve seen, that the § is replaced with -.

![image](https://cloud.githubusercontent.com/assets/18524580/21604288/ac5f09b6-d1a2-11e6-830c-3fafbf46ab83.png)

To verify, that there is a little bug, I´ve tested it with a dollar sign in the password. The escaping worked without any problem.

If you need additionally information feel free to ask.

Thanks
Have a nice day

**Comment by gilleslamiral** [comment]
Hi Hagen,

It is a windows batch escaping problem since when § character is put in a file
and passed to imapsync via --passfile1 there is no problem on Windows.
Also no problem either via --password1 on Unix.

I really don't know how to escape § in windows.
Here seems a solution:
http://www.dostips.com/forum/viewtopic.php?f=3&t=3857

If you find a simple one, tell me I'll update
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Windows.txt

Le 03/01/2017 à 10:55, Hagen Tasche a écrit :
> Hi and a happy new year!
>
> In the last days I´ve tested imapsync a little bit and detected a little bug.
> host2 is an Exchange server, Login is possible with a lot of other user/passwords
> imapsync in the latest version on Windows 7 x64 (Ger)
>
> In one of the passwords is a § Sign.
> For this, as example: The password is: Test§Test
>
> But I´ve got only "NO LOGIN failure" with this password.
> Tested: (And with 0167, A7 as ASCII code for the §)
> --password2 "Test§Test"
> --password2 Test§Test
> --password2 "Test^§Test"
> --password2 Test^§Test
> --password2 "Test\§Test"
> --password2 Test\§Test
> --password2 Test\§Test


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by Fvbor** [comment]
Hi Gilles,

ok thank you, that helped.
Have a nice day!
