### ISSUE TITLE
X-GM-RAW search exact phrase

### ISSUE THREAD

**Issue by mikerun** [imapsync/imapsync#90]
I can't seem to find a way to search for an exact phrase using X-GM-RAW
it should be possible by using double quotes as stated in 
https://support.google.com/mail/answer/7190?topic=41
using --search 'X-GM-RAW "search this phrase"' will get messages containing any of the words in the phrase 
do I need to add some-kind of escaping or more quotes
hope someone can help me with that

**Comment by gilleslamiral** [comment]
Hi Mike,

I've done some test and found that

   imapsync ... --search 'X-GM-RAW "search this phrase"'

gets all messages containing all of the words in the phrase, not any.
It's not "exact phrase" anyway.

Since double-quote " is also a special character in IMAP, in Perl, in Shell,
we face a classical headache here. I have to time to play
with this these days.

Le 28/02/2017 à 23:16, Mike Rundle a écrit :
> I can't seem to find a way to search for an exact phrase using X-GM-RAW
> it should be possible by using double quotes as stated in
> https://support.google.com/mail/answer/7190?topic=41
> using --search 'X-GM-RAW "search this phrase"' will get all messages containing any of the words in the phrase
> do I need to add some-kind of escaping or more quotes
> hope someone can help me with that


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by mikerun** [comment]
oh right just noticed now "all the words" not any but not the exact phrase
